web:
    image: pronovix/walkhub-service
    restart: always
    ports:
        - "80:80"
        - "443:443"
    links:
        - db
db:
    image: postgres:latest
    restart: always
    environment:
        POSTGRES_PASSWORD: docker
        POSTGRES_USER: docker
